@echo off
echo Starting OCPP Simulator...
echo Opening browser at http://localhost:8000...
start http://localhost:8000
echo Starting Python HTTP Server on port 8000...
python -m http.server 8000
pause
